title: "Network Visualizations in R"
subtitle: "using ggraph and graphlayouts"
description: | 
  An Introduction to Network Visualization in R using the packages ggraph and auxilliary packages
author: 
  - name: David Schoch
    orcid: 0000-0003-1689-0557
    email: david.schoch@gesis.org
    url: https://mr.schochastics.net
    affiliations:
      - name: GESIS - Leibniz Institute for the Social Sciences
toc: true
execute:
  freeze: true
  echo: true
  warning: false